import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from '../lib/registry'
import {ToastContainer} from "react-toastify";
import {SchoolProvider} from "@/contexts/SchoolContext";
import {ThemeProvider} from "@/components/ThemeProvider";
import {ErrorBoundary} from "@/components/ErrorBoundary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

          <StyledComponentsRegistry>
              <ThemeProvider>
                  <ErrorBoundary>
                      <SchoolProvider>{children}</SchoolProvider>
                  </ErrorBoundary>
              </ThemeProvider>
          </StyledComponentsRegistry>
          <ToastContainer />

      </body>
    </html>
  );
}
